Moved lau diagnostics to luarc; using treesitter for autopairs; added diffview, fugitive; diabled navic for bash and docker, replaced lualine-lsp-progress with fidget, improved neogit display and diffview integration, removed shfmt from null-ls, improved telescope display, formatted zsh with null-ls based beautysh

diff --git a/etc/home/zshrc b/etc/home/zshrc
--- a/etc/home/zshrc
+++ b/etc/home/zshrc
@@ -16,21 +16,21 @@ export ZSH="$HOME/.oh-my-zsh"
 ZSH_THEME="spaceship"
 
 SPACESHIP_PROMPT_ORDER=(
-  time          # Time stamps section
-  user          # Username section
-  dir           # Current directory section
-  host          # Hostname section
-  git           # Git section (git_branch + git_status)
-  pyenv         # Pyenv section
-  kubectl       # Kubectl context section
-  node
-  terraform     # Terraform workspace section
-  exec_time     # Execution time
-  line_sep      # Line break
-  vi_mode       # Vi-mode indicator
-  jobs          # Background jobs indicator
-  exit_code     # Exit code section
-  char          # Prompt character
+    time          # Time stamps section
+    user          # Username section
+    dir           # Current directory section
+    host          # Hostname section
+    git           # Git section (git_branch + git_status)
+    pyenv         # Pyenv section
+    kubectl       # Kubectl context section
+    node
+    terraform     # Terraform workspace section
+    exec_time     # Execution time
+    line_sep      # Line break
+    vi_mode       # Vi-mode indicator
+    jobs          # Background jobs indicator
+    exit_code     # Exit code section
+    char          # Prompt character
 )
 SPACESHIP_TIME_SHOW=true
 SPACESHIP_TIME_COLOR="blue"
@@ -103,19 +103,19 @@ forgit_checkout_branch=gcbf
 # Add wisely, as too many plugins slow down shell startup.
 # Keep zsh-syntax-highlighting as the last plugin
 plugins=(git gitfast docker colorize kubectl mosh pip ssh-agent sudo aws \
-    history-substring-search zsh-navigation-tools git-extras pyenv \
-    zsh-interactive-cd nvm \
-    # git@github.com:wfxr/forgit.git
+        history-substring-search zsh-navigation-tools git-extras pyenv \
+        zsh-interactive-cd nvm \
+        # git@github.com:wfxr/forgit.git
     forgit \
-    # git@github.com:hlissner/zsh-autopair.git
+        # git@github.com:hlissner/zsh-autopair.git
     zsh-autopair \
-    # git@github.com:Aloxaf/fzf-tab.git
+        # git@github.com:Aloxaf/fzf-tab.git
     fzf-tab \
-    # add plugins above this line
+        # add plugins above this line
     # git@github.com:zsh-users/zsh-autosuggestions.git
     zsh-autosuggestions \
-    # git@github.com:zsh-users/zsh-syntax-highlighting.git
-    zsh-syntax-highlighting )
+        # git@github.com:zsh-users/zsh-syntax-highlighting.git
+zsh-syntax-highlighting )
 
 source $ZSH/oh-my-zsh.sh
 
@@ -198,10 +198,10 @@ alias wget="noglob wget"
 
 # Neovim Remote Activation
 if [ -n "${NVIM}" ]; then
-  export NVIM_LISTEN_ADDRESS="$NVIM"
-  alias vims='nvr -o'
-  alias vimv='nvr -O'
-  alias vim='nvr --remote-tab'
+    export NVIM_LISTEN_ADDRESS="$NVIM"
+    alias vims='nvr -o'
+    alias vimv='nvr -O'
+    alias vim='nvr --remote-tab'
 fi
 
 # keybindings for history-substring-search
@@ -248,7 +248,7 @@ collate_k8s_context() {
     DEFAULT_KUBE_CONTEXTS="$HOME/.kube/config"
     if test -f "${DEFAULT_KUBE_CONTEXTS}"
     then
-    export KUBECONFIG="$DEFAULT_KUBE_CONTEXTS"
+        export KUBECONFIG="$DEFAULT_KUBE_CONTEXTS"
     fi
 
     CUSTOM_KUBE_CONTEXTS="$HOME/.kube/custom-contexts"
@@ -266,11 +266,9 @@ collate_k8s_context
 
 # to view path in readable format
 path() {
-    # old=$IFS
     local IFS=:
     pth=($=PATH)
     printf "%s\n" $pth
-    # IFS=$old
 }
 
 # zle custom functions
@@ -299,17 +297,17 @@ enable-fzf-tab
 
 # git commit browser
 function _git_log_zle {
-  git rev-parse HEAD > /dev/null 2>&1 || return
+    git rev-parse HEAD > /dev/null 2>&1 || return
 
-  local _gitLogLineToHash="echo {} | grep -o '[a-f0-9]\{7\}' | head -1"
-  local _viewGitLogLine="$_gitLogLineToHash | xargs -I % sh -c 'git show --color=always %'"
-  local _viewGitLogLineShort="$_gitLogLineToHash | xargs -I % sh -c 'git show --color=always --stat %'"
+    local _gitLogLineToHash="echo {} | grep -o '[a-f0-9]\{7\}' | head -1"
+    local _viewGitLogLine="$_gitLogLineToHash | xargs -I % sh -c 'git show --color=always %'"
+    local _viewGitLogLineShort="$_gitLogLineToHash | xargs -I % sh -c 'git show --color=always --stat %'"
 
-  git log --graph --color=always \
-    --format="%C(auto)%h%d %s %C(black)%C(bold)%cr% C(auto)%an" "$@" |
-  fzf --no-sort --reverse --tiebreak=index --no-multi \
-    --ansi --preview="$_viewGitLogLineShort" --preview-window=down \
-    --bind "enter:execute:$_viewGitLogLine | less -R && print $_gitLogLineToHash"
+    git log --graph --color=always \
+        --format="%C(auto)%h%d %s %C(black)%C(bold)%cr% C(auto)%an" "$@" |
+    fzf --no-sort --reverse --tiebreak=index --no-multi \
+        --ansi --preview="$_viewGitLogLineShort" --preview-window=down \
+        --bind "enter:execute:$_viewGitLogLine | less -R && print $_gitLogLineToHash"
 }
 
 function _git_log_zsh_wrapper {
@@ -322,67 +320,67 @@ bindkey '\ea' _git_log_zsh_wrapper
 
 # command history search
 __fzfcmd() {
-  [ -n "$TMUX_PANE" ] && { [ "${FZF_TMUX:-0}" != 0 ] || [ -n "$FZF_TMUX_OPTS" ]; } &&
+    [ -n "$TMUX_PANE" ] && { [ "${FZF_TMUX:-0}" != 0 ] || [ -n "$FZF_TMUX_OPTS" ]; } &&
     echo "fzf-tmux ${FZF_TMUX_OPTS:--d${FZF_TMUX_HEIGHT:-40%}} -- " || echo "fzf"
 }
 
 fzf-history-widget() {
-  local selected num
-  setopt localoptions noglobsubst noposixbuiltins pipefail no_aliases 2> /dev/null
-  selected=( $(fc -rl 1 | perl -ne 'print if !$seen{($_ =~ s/^\s*[0-9]+\s+//r)}++' |
+    local selected num
+    setopt localoptions noglobsubst noposixbuiltins pipefail no_aliases 2> /dev/null
+    selected=( $(fc -rl 1 | perl -ne 'print if !$seen{($_ =~ s/^\s*[0-9]+\s+//r)}++' |
     FZF_DEFAULT_OPTS="--height ${FZF_TMUX_HEIGHT:-40%} $FZF_DEFAULT_OPTS -n2..,.. --tiebreak=index --bind=ctrl-r:toggle-sort $FZF_CTRL_R_OPTS --query=${(qqq)LBUFFER} +m" $(__fzfcmd)) )
-  local ret=$?
-  if [ -n "$selected" ]; then
-    num=$selected[1]
-    if [ -n "$num" ]; then
-      zle vi-fetch-history -n $num
+    local ret=$?
+    if [ -n "$selected" ]; then
+        num=$selected[1]
+        if [ -n "$num" ]; then
+            zle vi-fetch-history -n $num
+        fi
     fi
-  fi
-  zle reset-prompt
-  return $ret
+    zle reset-prompt
+    return $ret
 }
 zle     -N   fzf-history-widget
 bindkey '^R' fzf-history-widget
 
 # edit a file under the current dir tree
 ve() {
-  local files
-  local IFS=$'\n' files=($(fzf-tmux --query="$1" --multi --select-1 --preview '
+    local files
+    local IFS=$'\n' files=($(fzf-tmux --query="$1" --multi --select-1 --preview '
     [[ $(file --mime {}) =~ binary ]] && echo {} is a binary file ||
-    (highlight -O ansi -l {} || cat {}) 2> /dev/null | head -100' \
-    --bind 'ctrl-n:page-down,ctrl-p:page-up,alt-j:preview-page-down,alt-k:preview-page-up'))
-  [[ -n "$files" ]] && vim -- "${files[@]}"
-  print "$files"
+            (highlight -O ansi -l {} || cat {}) 2> /dev/null | head -100' \
+        --bind 'ctrl-n:page-down,ctrl-p:page-up,alt-j:preview-page-down,alt-k:preview-page-up'))
+    [[ -n "$files" ]] && vim -- "${files[@]}"
+    print "$files"
 }
 
 # open after searching pattern in the file
 vg() {
-  local file
-  local line
+    local file
+    local line
 
-  read -r file line <<<"$(ag --nobreak --noheading --nocolor $@ . | \
+    read -r file line <<<"$(ag --nobreak --noheading --nocolor $@ . | \
       fzf-tmux --bind 'ctrl-n:page-down,ctrl-p:page-up' | \
       awk -F: '{print $1, $2}')"
 
-  if [[ -n "$file" ]]
-  then
-     vim "$file" +"$line"
-     print "$file" at "$line"
-  fi
+    if [[ -n "$file" ]]
+    then
+        vim "$file" +"$line"
+        print "$file" at "$line"
+    fi
 }
 
 # change to directory under the given or current directory
 ccd() {
-  local dir
-  dir=$(find ${1:-.} -path '*/\.*' -prune \
-                  -o -type d -print 2> /dev/null | fzf-tmux +m) &&
-  cd "$dir"
+    local dir
+    dir=$(find ${1:-.} -path '*/\.*' -prune \
+        -o -type d -print 2> /dev/null | fzf-tmux +m) &&
+    cd "$dir"
 }
 
 # homebrew with fzf
 bip() {
     local to_install=$( { brew formulae; brew casks; } | \
-        fzf-tmux ${FZF_DEFAULT_OPTS} \
+            fzf-tmux ${FZF_DEFAULT_OPTS} \
         -m --header='[brew:search]' --preview 'brew info {}')
 
     if [[ $to_install ]]; then
